version = 1

[qwen-dflash4]
# Download target: https://huggingface.co/bsaleh03/Qwen3.8-27B-ASCII-Condensed
model = /path/to/Qwen3.8-27B-ASCII-Condensed-UD-IQ4_XS.gguf

device = CUDA0
n-gpu-layers = all
fit = off

ctx-size = 50200
parallel = 1

flash-attn = on

cache-type-k = q4_0
cache-type-v = q4_0

spec-type = draft-dflash
# Download draft: https://huggingface.co/Blazestorm001/Qwen3.8-27B-ASCII-Condensed-DFlash2-GGUF
spec-draft-model = /path/to/Qwen3.8-27B-ASCII-Condensed-DFlash2-Q2_K.gguf
spec-draft-device = CUDA0
spec-draft-ngl = all
spec-draft-n-min = 0
spec-draft-n-max = 4
spec-draft-p-min = 0.0

cache-type-k-draft = q4_0
cache-type-v-draft = q4_0

load-mode = mmap

batch-size = 4096
ubatch-size = 512

temp = 1.0
top-k = 20
top-p = 0.95
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0

jinja = true
reasoning = on
chat-template-kwargs = {"reasoning_budget":1024, "reasoning_effort": "medium"}

load-on-startup = true
